// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'apply-dialogs'
  | 'apply-dialogs-description'
  | 'enabled'
  | 'fallback-win10'
  | 'fallback-win10-description'
  | 'material-acrylic'
  | 'material-label'
  | 'material-mica'
  | 'material-mica-alt'
  | 'prefs-title'
  | 'section-material'
  | 'status-disabled'
  | 'status-fallback'
  | 'status-full'
  | 'tint-opacity'
  | 'tint-opacity-description';
