// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "version": string;
      "enabled": boolean;
      "material": string;
      "tint-opacity": number;
      "apply-dialogs": boolean;
      "fallback-win10": boolean;
      "pdf-background": boolean;
    };
  }
}
